Fail unless changed

diff --git a/.github/workflows/release_from_changelog.yml b/.github/workflows/release_from_changelog.yml
--- a/.github/workflows/release_from_changelog.yml
+++ b/.github/workflows/release_from_changelog.yml
@@ -19,8 +19,12 @@ jobs:
         with:
           files: |
              CHANGELOG.md
+      - name: Fail Unless Changelog Changed
+        id: fail_if_changed
+        run: |
+              echo "::error file={name},line={line},endLine={endLine},title={title}::{message}"
+              exit 1
       - name: Get Changelog Entry
-        if: steps.verify-changed-files.outputs.files_changed == 'true'
         id: changelog_reader
         uses: mindsers/changelog-reader-action@v2
         with:
